arm:
  goal_joint_tolerance: 0.001
  goal_orientation_tolerance: 0.001
  goal_position_tolerance: 0.0001
  kinematics_solver: rm_65_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.05
