sensors:
  # - far_clipping_plane_distance: 1.0
  #   filtered_cloud_topic: filtered_cloud
  #   image_topic: /camera/aligned_depth_to_color/image_raw
  #   max_update_rate: 10.0
  #   near_clipping_plane_distance: 0.4
  #   padding_offset: 0.08
  #   padding_scale: 0.5
  #   max_resolution: 0.01
  #   queue_size: 5
  #   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   shadow_threshold: 0.2
  []